version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
   interval: "weekly"
   day: "friday"
   #8 AM MST
   time: "14:00"
  labels:
    - "dependencies"
    - "ok-to-test"
  open-pull-requests-limit: 20
